name: gh-action

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build:
    name: Build pizza shop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: softwaredeliverymanagement329/pizzashop
          path: source
          ref: "main"
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build project
        run: npm ci && npm run build

      - name: Checkout pages repo
        uses: actions/checkout@v4
        with:
          repository: softwaredeliverymanagement329/softwaredeliverymanagement329.github.io
          path: production
          ref: "main"
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Update pages repo
        shell: bash
        working-directory: "production"
        run: |
          ls -la ../production
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      # - run: ls -la site

      # - name: Upload Artifact
      #   if: github.ref == 'refs/heads/main'
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: "./dist"

      # - run: |
      #     git clone https://github.com/softwaredeliverymanagement329/softwaredeliverymanagement329.github.io.git site
      #     cd site
      #     printf "Hello from actions" > index.html
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "actions@github.com"
      #     git add .
      #     git commit -m "Triggered by build"
      #     git push

  # deploy:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   needs: build

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4

#        git push https://${{ secrets.API_TOKEN_GITHUB }}@github.com/your-org/destination-repo.git HEAD:main

