name: Build, Test, Deploy

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build:
    name: Build pizza shop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build project
        run: npm ci && npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Checkout pages repo
        uses: actions/checkout@v4
        with:
          repository: softwaredeliverymanagement329/softwaredeliverymanagement329.github.io
          path: production
          ref: 'main'
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Update pages repo
        shell: bash
        working-directory: 'production'
        run: |
          ls -la ..
          cp -r ../dist/* .
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push]
